// This file has been automatically generated by capnp-es.
import * as $ from "capnp-es";
export const _capnpFileId = BigInt("0xd7b95c53e5042a1b");
export class Basic extends $.Struct {
  static _capnp = {
    displayName: "Basic",
    id: "be3c40e060e06605",
    size: new $.ObjectSize(0, 2)
  };
  get name() {
    return $.utils.getText(0, this);
  }
  set name(value) {
    $.utils.setText(0, value, this);
  }
  get email() {
    return $.utils.getText(1, this);
  }
  set email(value) {
    $.utils.setText(1, value, this);
  }
  toString() {
    return "Basic_" + super.toString();
  }
}
